language: java

sudo: false

jdk:
- openjdk8

services:
- docker

before_install:
- export AWS_ACCESS_KEY_ID=ThisIsTheAccessKeyId
- export AWS_SECRET_ACCESS_KEY=ThisIsRequiredButNotUsed
- docker pull amazon/dynamodb-local
- docker run -d -p 8000:8000 amazon/dynamodb-local
- docker ps -a
- echo "$AWS_ACCESS_KEY_ID"
