language: java

sudo: false

jdk:
  - openjdk8

services:
  - docker

before_install:
  - docker pull amazon/dynamodb-local
  - docker run -d -p 8000:8000 amazon/dynamodb-local
  - docker ps -a # Display all the dockers
  - echo "$AWS_ACCESS_KEY_ID"
